import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
{/* On this page, the default header and footer will be constant throughout every sub-page and the {children}
    section will change according to the content of that specific page */}


        <header>
          <div className="logo">
          <Link href="/">
            <Image src="/picture/logo4.png" alt="RD as Dzeinse Enterprise for the logo" width={120} height={60} className="logo-img" />
          </Link>
          </div>
          <nav className="navigation">
          <ul>
            <li><Link href="/" className="sub-sections">Home</Link></li>
            <li><Link href="/projects" className="sub-sections">Projects</Link></li>
            <li><Link href="/quotegen" className="sub-sections">Quote Generator</Link></li>
            <li><Link href="/insights" className="sub-sections">Insights</Link></li>
          </ul>

          </nav>
        </header>
      
        <main>
          {children}
        </main>


















        <footer>
          <div className="footer-content">

            <Link href="/">
              <Image src="/picture/logo4.png" alt="RD as Dzeinse Enterprise for the logo" width={50} height={50} className="logo-img footer-logo-img" />
            </Link>

            <div className="leftside">
              <p>Explore</p>
              <div className="footer-links">
                <ul>
                  <li><Link href="/" className="link-color">Home</Link></li>
                  <li><Link href="/projects" className="link-color">Projects</Link></li>
                  <li><Link href="/quotegen" className="link-color">Quote Generator</Link></li>
                  <li><Link href="/insights" className="link-color">Insights</Link></li>
                </ul>
              </div>
            </div>

            <div className="rightside">
              <p id="firstp-tag">Thank you for visiting</p>
              <p>© 2025 Romain Dzeinse. All rights reserved.</p>
            </div>
          </div>

        </footer>

      </body>
    </html>
  );
}
